spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
external-exchange:
  base-url: https://api.exchangeratesapi.io/v1
  access-key: ${EXCHANGE_API_KEY}
  base-currency: EUR
  supported-currencies: USD,KZT,RUB

resilience4j:
  retry:
    instances:
      exchange-rate:
        maxAttempts: 3
        waitDuration: 2s