spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
external-exchange:
  base-url: https://api.exchangeratesapi.io/v1
  access-key: ${EXCHANGE_API_KEY}
  base-currency: EUR
  supported-currencies: USD,KZT,RUB